import { Formation, FormationId, Player, Role, Slot, Squad } from "@/data/types";
const slot=(id:string,role:Role,label:string,x:number,y:number):Slot=>({id,role,label,x,y});
export const formations:Record<FormationId,Formation>={
 "4-3-3":{id:"4-3-3",name:"4 · 3 · 3",description:"Width and control",slots:[slot("lw","LW","Left wing",18,15),slot("st","ST","Striker",50,12),slot("rw","RW","Right wing",82,15),slot("cm1","CM","Midfield",25,42),slot("cm2","CM","Midfield",50,47),slot("cm3","CM","Midfield",75,42),slot("lb","LB","Left back",12,72),slot("cb1","CB","Centre back",37,68),slot("cb2","CB","Centre back",63,68),slot("rb","RB","Right back",88,72),slot("gk","GK","Goalkeeper",50,90)]},
 "4-4-2":{id:"4-4-2",name:"4 · 4 · 2",description:"Classic and balanced",slots:[slot("st1","ST","Striker",36,15),slot("st2","ST","Striker",64,15),slot("lw","LW","Left midfield",12,45),slot("cm1","CM","Central midfield",38,45),slot("cm2","CM","Central midfield",62,45),slot("rw","RW","Right midfield",88,45),slot("lb","LB","Left back",12,72),slot("cb1","CB","Centre back",37,68),slot("cb2","CB","Centre back",63,68),slot("rb","RB","Right back",88,72),slot("gk","GK","Goalkeeper",50,90)]},
 "4-2-3-1":{id:"4-2-3-1",name:"4 · 2 · 3 · 1",description:"Layers between the lines",slots:[slot("st","ST","Striker",50,10),slot("lw","LW","Left attack",18,34),slot("cam","CM","Attacking midfield",50,32),slot("rw","RW","Right attack",82,34),slot("cm1","CM","Holding midfield",35,55),slot("cm2","CM","Holding midfield",65,55),slot("lb","LB","Left back",12,76),slot("cb1","CB","Centre back",37,72),slot("cb2","CB","Centre back",63,72),slot("rb","RB","Right back",88,76),slot("gk","GK","Goalkeeper",50,92)]},
 "3-4-3":{id:"3-4-3",name:"3 · 4 · 3",description:"Brave and aggressive",slots:[slot("lw1","LW","Left wing",18,14),slot("st","ST","Striker",50,10),slot("rw1","RW","Right wing",82,14),slot("lw2","LW","Left midfield",10,47),slot("cm1","CM","Central midfield",37,48),slot("cm2","CM","Central midfield",63,48),slot("rw2","RW","Right midfield",90,47),slot("cb1","CB","Centre back",25,72),slot("cb2","CB","Centre back",50,68),slot("cb3","CB","Centre back",75,72),slot("gk","GK","Goalkeeper",50,91)]}
};
export const formationList=Object.values(formations);
export const fits=(player:Player,role:Role)=>player.position===role||player.alt.includes(role);
export const availableSlots=(player:Player,xi:Record<string,Player>,slots:Slot[])=>slots.filter(s=>!xi[s.id]&&fits(player,s.role));
export const drawSquad=(all:Squad[],previous?:string)=>{const pool=all.filter(s=>s.id!==previous);return pool[Math.floor(Math.random()*pool.length)]??all[0]};
export type Result={score:number;attack:number;defense:number;tier:string;wins:number;losses:number};
const average=(values:number[])=>Math.round(values.reduce((sum,n)=>sum+n,0)/values.length*10)/10;
export const calculate=(xi:Record<string,Player>,slots:Slot[]):Result=>{const entries=Object.entries(xi).map(([id,p])=>({player:p,slot:slots.find(s=>s.id===id)!}));const score=average(entries.map(({player})=>player.rating));const attack=average(entries.filter(({slot})=>slot.y<40).map(({player})=>player.rating));const defense=average(entries.filter(({slot})=>slot.y>60).map(({player})=>player.rating));const [tier,wins]=score>=90?["S",8]:score>=87?["A+",7]:score>=84?["A",6]:score>=81?["B+",5]:score>=78?["B",4]:score>=75?["C",3]:["D",2];return{score,attack,defense,tier,wins,losses:8-wins}};
