"use client";
import { useMemo, useState } from "react";
import { squads } from "@/data/squads";
import { zhClubs, zhPlayers } from "@/data/zh";
import generatedZh from "@/data/generatedZh.json";
import { FormationId, Player, Squad } from "@/data/types";
import { availableSlots, calculate, drawSquad, formationList, formations } from "@/lib/game";
type Screen="home"|"setup"|"game";
type Lang="en"|"zh-CN";
const copy={en:{tagline:"Four tournaments. One immortal XI.",intro:"Build your shape, spin for a World Cup squad, and draft eleven players without ever seeing their rating.",play:"PLAY",back:"Back",setup:"Match setup",choose:"Choose your game",era:"Era",yearRange:"Year range",coming:"More eras coming",range:"2010—2022",rangeNote:"Four most recent completed World Cups",shape:"Shape",formation:"Formation",start:"START WITH",newGame:"New game",pick:"Pick",ready:"Ready for pick",drawing:"Drawing your pool",spinHelp:"Press the button to draw a random champion squad and reveal the available players.",fetch:"FETCH RANDOM SQUAD",spinning:"SPINNING…",yourPool:"Your pool",players:"players",season:"Season complete",score:"Hidden squad score",again:"PLAY AGAIN",choosePosition:"Choose a position",draft:"DRAFT",stats:["Club goals","Club assists","Titles","Cups","Intl goals","Caps"],formationNotes:{"4-3-3":"Width and control","4-4-2":"Classic and balanced","4-2-3-1":"Layers between the lines","3-4-3":"Brave and aggressive"}},"zh-CN":{tagline:"四届世界杯，一支不朽十一人。",intro:"选择阵型，抽取世界杯球队，在看不到评分的情况下选出十一名球员。",play:"开始游戏",back:"返回",setup:"比赛设置",choose:"选择游戏模式",era:"年代",yearRange:"年份范围",coming:"更多年代即将推出",range:"2010—2022",rangeNote:"最近四届已完成的男子世界杯",shape:"阵型",formation:"选择阵型",start:"使用阵型开始",newGame:"新游戏",pick:"第",ready:"准备第",drawing:"正在抽取球队",spinHelp:"点击按钮随机抽取一支世界杯冠军队，并查看可选球员。",fetch:"抽取随机球队",spinning:"抽取中…",yourPool:"可选球员",players:"名球员",season:"赛季完成",score:"隐藏阵容评分",again:"再玩一次",choosePosition:"选择位置",draft:"选择",stats:["俱乐部进球","俱乐部助攻","冠军","杯赛冠军","国家队进球","国家队出场"],formationNotes:{"4-3-3":"边路宽度与中场控制","4-4-2":"经典且平衡","4-2-3-1":"层次分明，控制肋部","3-4-3":"勇敢且富有攻击性"}}} as const;
const countryNames:Record<Lang,Record<string,string>>={en:{},"zh-CN":{Australia:"澳大利亚",Japan:"日本","South Korea":"韩国",Morocco:"摩洛哥",Senegal:"塞内加尔",Brazil:"巴西",Uruguay:"乌拉圭",Colombia:"哥伦比亚",Peru:"秘鲁",England:"英格兰",Poland:"波兰",Portugal:"葡萄牙",Sweden:"瑞典",Croatia:"克罗地亚",Belgium:"比利时",Denmark:"丹麦",Spain:"西班牙",Germany:"德国",France:"法国",Argentina:"阿根廷"}};
const allZhPlayers:Record<string,string>={...(generatedZh.players as Record<string,string>),...zhPlayers};
const allZhClubs:Record<string,string>={...(generatedZh.clubs as Record<string,string>),...zhClubs};
const roleNames:Record<Lang,Record<string,string>>={en:{GK:"Goalkeeper",LB:"Left back",CB:"Centre back",RB:"Right back",CM:"Midfield",LW:"Left wing",ST:"Striker",RW:"Right wing"},"zh-CN":{GK:"守门员",LB:"左后卫",CB:"中后卫",RB:"右后卫",CM:"中场",LW:"左边锋",ST:"前锋",RW:"右边锋"}};
const resultCopy={en:{score:"Team rating",attack:"ATT",defense:"DEF"},"zh-CN":{score:"球队评分",attack:"进攻",defense:"防守"}} as const;
function LanguageToggle({lang,setLang}:{lang:Lang;setLang:(lang:Lang)=>void}){return <div className="inline-flex rounded-full border border-white/15 bg-black/15 p-1 text-xs"><button onClick={()=>setLang("en")} className={`rounded-full px-3 py-1.5 ${lang==="en"?"bg-lime text-ink":"text-white/50"}`}>EN</button><button onClick={()=>setLang("zh-CN")} className={`rounded-full px-3 py-1.5 ${lang==="zh-CN"?"bg-lime text-ink":"text-white/50"}`}>简体中文</button></div>}
const Stat=({n,label}:{n:number;label:string})=><div><b className="display text-xl text-lime">{n}</b><span className="block text-[10px] uppercase tracking-wider text-white/45">{label}</span></div>;
function PlayerCard({p,onPick,disabled,lang}:{p:Player;onPick:(p:Player)=>void;disabled:boolean;lang:Lang}){const t=copy[lang];const name=lang==="zh-CN"?(allZhPlayers[p.name]??p.name):p.name;const club=lang==="zh-CN"?(allZhClubs[p.club]??p.club):p.club;return <details className="group border-b border-white/10 bg-white/[.025] open:bg-white/[.06]"><summary className="flex cursor-pointer items-center gap-3 p-4"><span className="display w-9 text-sm text-lime">{p.position}</span><span className="min-w-0 flex-1"><b className="display block truncate text-lg leading-none">{name}</b><small className="text-white/45">{club}</small></span><button onClick={e=>{e.preventDefault();onPick(p)}} disabled={disabled} className="rounded-full bg-lime px-4 py-2 text-xs font-bold text-ink disabled:cursor-not-allowed disabled:bg-white/10 disabled:text-white/25">{t.draft}</button><span className="text-white/35 group-open:rotate-180">⌄</span></summary><div className="grid grid-cols-3 gap-3 px-4 pb-4 text-center"><Stat n={p.stats.clubGoals} label={t.stats[0]}/><Stat n={p.stats.clubAssists} label={t.stats[1]}/><Stat n={p.stats.trophies} label={t.stats[2]}/><Stat n={p.stats.cups} label={t.stats[3]}/><Stat n={p.stats.internationalGoals} label={t.stats[4]}/><Stat n={p.stats.caps} label={t.stats[5]}/></div></details>}
export default function Game(){
 const [lang,setLang]=useState<Lang>("en");const t=copy[lang];const [screen,setScreen]=useState<Screen>("home");const [formationId,setFormationId]=useState<FormationId>("4-3-3");const formation=formations[formationId];const [squad,setSquad]=useState<Squad|null>(null);const [reel,setReel]=useState<Squad>(squads[0]);const [drawnIds,setDrawnIds]=useState<string[]>([]);const [spinning,setSpinning]=useState(false);const [xi,setXi]=useState<Record<string,Player>>({});const [pending,setPending]=useState<Player|null>(null);const picks=Object.keys(xi).length;const done=picks===11;const result=useMemo(()=>done?calculate(xi,formation.slots):null,[done,xi,formation.slots]);
 const begin=()=>{setXi({});setPending(null);setSquad(null);setDrawnIds([]);setScreen("game")};
 const reset=()=>{setXi({});setPending(null);setSquad(null);setDrawnIds([]);setSpinning(false);setScreen("setup")};
 const roll=()=>{if(spinning)return;setSquad(null);setSpinning(true);let ticks=0;const timer=window.setInterval(()=>{setReel(squads[Math.floor(Math.random()*squads.length)]);ticks++;if(ticks>=13){window.clearInterval(timer);const remaining=squads.filter(s=>!drawnIds.includes(s.id));const pool=remaining.length?remaining:squads;const final=drawSquad(pool);setDrawnIds(previous=>previous.length>=squads.length?[final.id]:[...previous,final.id]);setReel(final);setSquad(final);setSpinning(false)}},95)};
 const pick=(p:Player)=>{const possible=availableSlots(p,xi,formation.slots);if(possible.length===1)place(p,possible[0].id);else setPending(p)};
 const place=(p:Player,id:string)=>{setXi({...xi,[id]:p});setPending(null);setSquad(null)};
 if(screen==="home")return <main className="noise relative flex min-h-screen items-center justify-center p-6"><div className="absolute right-5 top-5"><LanguageToggle lang={lang} setLang={setLang}/></div><div className="max-w-3xl text-center"><div className="mb-5 text-6xl">⚽</div><p className="mb-3 text-xs font-bold uppercase tracking-[.35em] text-lime">{t.tagline}</p><h1 className="display text-7xl font-extrabold leading-[.82] sm:text-9xl">World Cup<br/><span className="text-lime">XI</span></h1><p className="mx-auto mt-7 max-w-xl text-white/60">{t.intro}</p><button onClick={()=>setScreen("setup")} className="mt-9 rounded-full bg-lime px-8 py-4 font-bold text-ink shadow-[0_0_50px_rgba(216,255,98,.25)]">{t.play} →</button></div></main>;
 if(screen==="setup")return <main className="noise min-h-screen p-5 sm:p-10"><div className="mx-auto max-w-5xl"><div className="flex items-center justify-between"><button onClick={()=>setScreen("home")} className="text-sm text-white/45 hover:text-white">← {t.back}</button><LanguageToggle lang={lang} setLang={setLang}/></div><p className="mt-10 text-xs font-bold uppercase tracking-[.3em] text-lime">{t.setup}</p><h1 className="display mt-2 text-5xl sm:text-7xl">{t.choose}</h1><section className="mt-10"><div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-white/40">01 · {t.era}</p><h2 className="display text-3xl">{t.yearRange}</h2></div><span className="rounded-full bg-white/5 px-3 py-1 text-xs text-white/35">{t.coming}</span></div><button className="w-full rounded-2xl border border-lime bg-lime/10 p-5 text-left"><b className="display text-2xl">{t.range}</b><span className="mt-1 block text-sm text-white/50">{t.rangeNote}</span></button></section><section className="mt-10"><p className="text-xs font-bold uppercase tracking-widest text-white/40">02 · {t.shape}</p><h2 className="display mt-1 text-3xl">{t.formation}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{formationList.map(f=><button key={f.id} onClick={()=>setFormationId(f.id)} className={`rounded-2xl border p-5 text-left transition ${formationId===f.id?"border-lime bg-lime text-ink":"border-white/10 bg-white/[.03] hover:border-white/30"}`}><b className="display block text-3xl">{f.name}</b><span className={`text-xs ${formationId===f.id?"text-ink/60":"text-white/40"}`}>{t.formationNotes[f.id]}</span><div className="relative mt-5 h-24 rounded-lg bg-black/10">{f.slots.map(s=><i key={s.id} className={`absolute h-2 w-2 -translate-x-1/2 -translate-y-1/2 rounded-full ${formationId===f.id?"bg-ink":"bg-lime"}`} style={{left:`${s.x}%`,top:`${s.y}%`}}/>)}</div></button>)}</div></section><button onClick={begin} className="mt-10 w-full rounded-full bg-lime px-8 py-4 font-bold text-ink sm:w-auto">{t.start} {formation.name} →</button></div></main>;
 return <main className="min-h-screen bg-ink"><header className="sticky top-0 z-20 flex items-center justify-between gap-3 border-b border-white/10 bg-ink/90 px-5 py-3 backdrop-blur"><b className="display text-2xl">WORLD CUP <span className="text-lime">XI</span></b><div className="text-xs font-bold uppercase tracking-widest text-white/50">{formation.name} · {t.pick} <span className="text-white">{Math.min(picks+1,11)}</span> / 11</div><div className="flex items-center gap-3"><LanguageToggle lang={lang} setLang={setLang}/><button onClick={reset} className="hidden text-xs text-white/45 hover:text-white sm:block">{t.newGame}</button></div></header>
 <div className="grid lg:grid-cols-[minmax(500px,1.05fr)_minmax(400px,.8fr)]"><section className="flex min-h-[calc(100vh-57px)] items-center p-4 sm:p-7"><div className="pitch-lines relative mx-auto h-[720px] w-full max-w-[680px] overflow-hidden rounded-[32px] border border-white/15 bg-pitch shadow-2xl"><div className="absolute inset-5 rounded-[22px] border border-white/15"/><div className="absolute left-1/2 top-1/2 h-32 w-32 -translate-x-1/2 -translate-y-1/2 rounded-full border border-white/15"/><div className="absolute left-1/2 top-5 h-24 w-56 -translate-x-1/2 border border-t-0 border-white/15"/><div className="absolute bottom-5 left-1/2 h-24 w-56 -translate-x-1/2 border border-b-0 border-white/15"/>{formation.slots.map(s=>{const p=xi[s.id];return <div key={s.id} style={{left:`${s.x}%`,top:`${s.y}%`}} className="absolute w-[23%] -translate-x-1/2 -translate-y-1/2 text-center"><div className={`mx-auto flex min-h-[72px] flex-col justify-center rounded-2xl border px-2 py-2 shadow-lg backdrop-blur ${p?"border-lime/70 bg-lime text-ink":"border-dashed border-white/30 bg-black/25 text-white/45"}`}><b className="display truncate text-sm sm:text-base">{p?(lang==="zh-CN"?(allZhPlayers[p.name]??p.name):p.name):s.role}</b><small className="truncate text-[9px] font-bold uppercase opacity-60">{p?`${countryNames[lang][p.country]??p.country} · ${p.year}`:(roleNames[lang][s.role]??s.label)}</small></div></div>})}</div></section>
 <aside className="min-h-[calc(100vh-57px)] border-l border-white/10 bg-[#0b1711] p-5 sm:p-7">{result?<div className="flex min-h-[70vh] flex-col items-center justify-center text-center"><p className="text-xs font-bold uppercase tracking-[.3em] text-lime">{t.season}</p><div className="display mt-2 text-[10rem] font-extrabold leading-none text-lime">{result.tier}</div><div className="my-5 grid w-full max-w-sm grid-cols-3 gap-3"><div className="rounded-2xl bg-white/5 p-4"><span className="text-xs text-white/40">{resultCopy[lang].attack}</span><b className="display block text-3xl text-lime">{result.attack}</b></div><div className="rounded-2xl border border-lime/30 bg-lime/10 p-4"><span className="text-xs text-white/40">{resultCopy[lang].score}</span><b className="display block text-3xl text-lime">{result.score}</b></div><div className="rounded-2xl bg-white/5 p-4"><span className="text-xs text-white/40">{resultCopy[lang].defense}</span><b className="display block text-3xl text-lime">{result.defense}</b></div></div><h2 className="display text-6xl">{result.wins}–{result.losses}</h2><button onClick={reset} className="mt-8 rounded-full bg-lime px-7 py-3 font-bold text-ink">{t.again}</button></div>:!squad?<div className="flex min-h-[70vh] flex-col items-center justify-center text-center"><p className="text-xs font-bold uppercase tracking-[.3em] text-lime">{spinning?t.drawing:`${t.ready} ${picks+1}`}</p><div className={`my-7 w-full overflow-hidden rounded-3xl border border-white/15 bg-black/20 p-7 ${spinning?"slot-reel":""}`}><div className="text-6xl">{reel.flag}</div><h2 className="display mt-3 text-5xl">{countryNames[lang][reel.country]??reel.country}</h2><div className="display mt-1 text-3xl text-lime">{reel.year}</div></div><p className="max-w-sm text-sm text-white/40">{t.spinHelp}</p><button onClick={roll} disabled={spinning} className="mt-7 rounded-full bg-lime px-8 py-4 font-bold text-ink disabled:animate-pulse disabled:opacity-60">{spinning?t.spinning:`${t.fetch} →`}</button></div>:<><div className="mb-5 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.3em] text-lime">{t.pick} {picks+1} · {t.yourPool}</p><h2 className="display text-4xl font-extrabold">{squad.flag} {countryNames[lang][squad.country]??squad.country} <span className="text-white/35">{squad.year}</span></h2></div><span className="text-xs text-white/35">{squad.players.length} {t.players}</span></div><div className="max-h-[calc(100vh-180px)] overflow-y-auto rounded-2xl border border-white/10">{squad.players.map(p=><PlayerCard key={p.id} p={p} lang={lang} onPick={pick} disabled={availableSlots(p,xi,formation.slots).length===0}/>)}</div></>}</aside></div>
 {pending&&<div className="fixed inset-0 z-30 flex items-end justify-center bg-black/70 p-4 sm:items-center" onClick={()=>setPending(null)}><div className="w-full max-w-md rounded-3xl border border-white/15 bg-[#132219] p-6" onClick={e=>e.stopPropagation()}><p className="text-xs uppercase tracking-widest text-lime">{t.choosePosition}</p><h3 className="display mt-1 text-3xl">{lang==="zh-CN"?(allZhPlayers[pending.name]??pending.name):pending.name}</h3><div className="mt-5 grid grid-cols-2 gap-3">{availableSlots(pending,xi,formation.slots).map(s=><button key={s.id} onClick={()=>place(pending,s.id)} className="rounded-xl border border-white/15 p-4 text-left hover:border-lime hover:bg-lime hover:text-ink"><b className="display block text-xl">{s.role}</b><small>{roleNames[lang][s.role]??s.label}</small></button>)}</div></div></div>}
 </main>
}
