"use client";
import { useMemo, useState } from "react";
import { squads } from "@/data/squads";
import { FormationId, Player, Squad } from "@/data/types";
import { availableSlots, calculate, drawSquad, formationList, formations } from "@/lib/game";
type Screen="home"|"setup"|"game";
const Stat=({n,label}:{n:number;label:string})=><div><b className="display text-xl text-lime">{n}</b><span className="block text-[10px] uppercase tracking-wider text-white/45">{label}</span></div>;
function PlayerCard({p,onPick,disabled}:{p:Player;onPick:(p:Player)=>void;disabled:boolean}){return <details className="group border-b border-white/10 bg-white/[.025] open:bg-white/[.06]"><summary className="flex cursor-pointer items-center gap-3 p-4"><span className="display w-9 text-sm text-lime">{p.position}</span><span className="min-w-0 flex-1"><b className="display block truncate text-lg leading-none">{p.name}</b><small className="text-white/45">{p.club}</small></span><button onClick={e=>{e.preventDefault();onPick(p)}} disabled={disabled} className="rounded-full bg-lime px-4 py-2 text-xs font-bold text-ink disabled:cursor-not-allowed disabled:bg-white/10 disabled:text-white/25">DRAFT</button><span className="text-white/35 group-open:rotate-180">⌄</span></summary><div className="grid grid-cols-3 gap-3 px-4 pb-4 text-center"><Stat n={p.stats.clubGoals} label="Club goals"/><Stat n={p.stats.clubAssists} label="Club assists"/><Stat n={p.stats.trophies} label="Titles"/><Stat n={p.stats.cups} label="Cups"/><Stat n={p.stats.internationalGoals} label="Intl goals"/><Stat n={p.stats.caps} label="Caps"/></div></details>}
export default function Game(){
 const [screen,setScreen]=useState<Screen>("home");const [formationId,setFormationId]=useState<FormationId>("4-3-3");const formation=formations[formationId];const [squad,setSquad]=useState<Squad|null>(null);const [reel,setReel]=useState<Squad>(squads[0]);const [spinning,setSpinning]=useState(false);const [xi,setXi]=useState<Record<string,Player>>({});const [pending,setPending]=useState<Player|null>(null);const picks=Object.keys(xi).length;const done=picks===11;const result=useMemo(()=>done?calculate(xi,formation.slots):null,[done,xi,formation.slots]);
 const begin=()=>{setXi({});setPending(null);setSquad(null);setScreen("game")};
 const reset=()=>{setXi({});setPending(null);setSquad(null);setSpinning(false);setScreen("setup")};
 const roll=()=>{if(spinning)return;setSquad(null);setSpinning(true);let ticks=0;const timer=window.setInterval(()=>{setReel(squads[Math.floor(Math.random()*squads.length)]);ticks++;if(ticks>=13){window.clearInterval(timer);const final=drawSquad(squads);setReel(final);setSquad(final);setSpinning(false)}},95)};
 const pick=(p:Player)=>{const possible=availableSlots(p,xi,formation.slots);if(possible.length===1)place(p,possible[0].id);else setPending(p)};
 const place=(p:Player,id:string)=>{setXi({...xi,[id]:p});setPending(null);setSquad(null)};
 if(screen==="home")return <main className="noise flex min-h-screen items-center justify-center p-6"><div className="max-w-3xl text-center"><div className="mb-5 text-6xl">⚽</div><p className="mb-3 text-xs font-bold uppercase tracking-[.35em] text-lime">Four tournaments. One immortal XI.</p><h1 className="display text-7xl font-extrabold leading-[.82] sm:text-9xl">World Cup<br/><span className="text-lime">XI</span></h1><p className="mx-auto mt-7 max-w-xl text-white/60">Build your shape, spin for a World Cup squad, and draft eleven players without ever seeing their rating.</p><button onClick={()=>setScreen("setup")} className="mt-9 rounded-full bg-lime px-8 py-4 font-bold text-ink shadow-[0_0_50px_rgba(216,255,98,.25)]">PLAY →</button></div></main>;
 if(screen==="setup")return <main className="noise min-h-screen p-5 sm:p-10"><div className="mx-auto max-w-5xl"><button onClick={()=>setScreen("home")} className="text-sm text-white/45 hover:text-white">← Back</button><p className="mt-10 text-xs font-bold uppercase tracking-[.3em] text-lime">Match setup</p><h1 className="display mt-2 text-5xl sm:text-7xl">Choose your game</h1><section className="mt-10"><div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-white/40">01 · Era</p><h2 className="display text-3xl">Year range</h2></div><span className="rounded-full bg-white/5 px-3 py-1 text-xs text-white/35">More eras coming</span></div><button className="w-full rounded-2xl border border-lime bg-lime/10 p-5 text-left"><b className="display text-2xl">2010—2022</b><span className="mt-1 block text-sm text-white/50">Four most recent completed World Cups</span></button></section><section className="mt-10"><p className="text-xs font-bold uppercase tracking-widest text-white/40">02 · Shape</p><h2 className="display mt-1 text-3xl">Formation</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{formationList.map(f=><button key={f.id} onClick={()=>setFormationId(f.id)} className={`rounded-2xl border p-5 text-left transition ${formationId===f.id?"border-lime bg-lime text-ink":"border-white/10 bg-white/[.03] hover:border-white/30"}`}><b className="display block text-3xl">{f.name}</b><span className={`text-xs ${formationId===f.id?"text-ink/60":"text-white/40"}`}>{f.description}</span><div className="relative mt-5 h-24 rounded-lg bg-black/10">{f.slots.map(s=><i key={s.id} className={`absolute h-2 w-2 -translate-x-1/2 -translate-y-1/2 rounded-full ${formationId===f.id?"bg-ink":"bg-lime"}`} style={{left:`${s.x}%`,top:`${s.y}%`}}/>)}</div></button>)}</div></section><button onClick={begin} className="mt-10 w-full rounded-full bg-lime px-8 py-4 font-bold text-ink sm:w-auto">START WITH {formation.name} →</button></div></main>;
 return <main className="min-h-screen bg-ink"><header className="sticky top-0 z-20 flex items-center justify-between border-b border-white/10 bg-ink/90 px-5 py-3 backdrop-blur"><b className="display text-2xl">WORLD CUP <span className="text-lime">XI</span></b><div className="text-xs font-bold uppercase tracking-widest text-white/50">{formation.name} · Pick <span className="text-white">{Math.min(picks+1,11)}</span> / 11</div><button onClick={reset} className="text-xs text-white/45 hover:text-white">New game</button></header>
 <div className="grid lg:grid-cols-[minmax(500px,1.05fr)_minmax(400px,.8fr)]"><section className="flex min-h-[calc(100vh-57px)] items-center p-4 sm:p-7"><div className="pitch-lines relative mx-auto h-[720px] w-full max-w-[680px] overflow-hidden rounded-[32px] border border-white/15 bg-pitch shadow-2xl"><div className="absolute inset-5 rounded-[22px] border border-white/15"/><div className="absolute left-1/2 top-1/2 h-32 w-32 -translate-x-1/2 -translate-y-1/2 rounded-full border border-white/15"/><div className="absolute left-1/2 top-5 h-24 w-56 -translate-x-1/2 border border-t-0 border-white/15"/><div className="absolute bottom-5 left-1/2 h-24 w-56 -translate-x-1/2 border border-b-0 border-white/15"/>{formation.slots.map(s=>{const p=xi[s.id];return <div key={s.id} style={{left:`${s.x}%`,top:`${s.y}%`}} className="absolute w-[23%] -translate-x-1/2 -translate-y-1/2 text-center"><div className={`mx-auto flex min-h-[72px] flex-col justify-center rounded-2xl border px-2 py-2 shadow-lg backdrop-blur ${p?"border-lime/70 bg-lime text-ink":"border-dashed border-white/30 bg-black/25 text-white/45"}`}><b className="display truncate text-sm sm:text-base">{p?.name??s.role}</b><small className="truncate text-[9px] font-bold uppercase opacity-60">{p?`${p.country} · ${p.year}`:s.label}</small></div></div>})}</div></section>
 <aside className="min-h-[calc(100vh-57px)] border-l border-white/10 bg-[#0b1711] p-5 sm:p-7">{result?<div className="flex min-h-[70vh] flex-col items-center justify-center text-center"><p className="text-xs font-bold uppercase tracking-[.3em] text-lime">Season complete</p><div className="display mt-2 text-[10rem] font-extrabold leading-none text-lime">{result.tier}</div><h2 className="display text-6xl">{result.wins}–{result.losses}</h2><p className="mt-3 text-white/45">Hidden squad score: {result.score}</p><button onClick={reset} className="mt-8 rounded-full bg-lime px-7 py-3 font-bold text-ink">PLAY AGAIN</button></div>:!squad?<div className="flex min-h-[70vh] flex-col items-center justify-center text-center"><p className="text-xs font-bold uppercase tracking-[.3em] text-lime">{spinning?"Drawing your pool":"Ready for pick " + (picks+1)}</p><div className={`my-7 w-full overflow-hidden rounded-3xl border border-white/15 bg-black/20 p-7 ${spinning?"slot-reel":""}`}><div className="text-6xl">{reel.flag}</div><h2 className="display mt-3 text-5xl">{reel.country}</h2><div className="display mt-1 text-3xl text-lime">{reel.year}</div></div><p className="max-w-sm text-sm text-white/40">Press the button to draw a random champion squad and reveal the available players.</p><button onClick={roll} disabled={spinning} className="mt-7 rounded-full bg-lime px-8 py-4 font-bold text-ink disabled:animate-pulse disabled:opacity-60">{spinning?"SPINNING…":"FETCH RANDOM SQUAD →"}</button></div>:<><div className="mb-5 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.3em] text-lime">Pick {picks+1} · Your pool</p><h2 className="display text-4xl font-extrabold">{squad.flag} {squad.country} <span className="text-white/35">{squad.year}</span></h2></div><span className="text-xs text-white/35">{squad.players.length} players</span></div><div className="max-h-[calc(100vh-180px)] overflow-y-auto rounded-2xl border border-white/10">{squad.players.map(p=><PlayerCard key={p.id} p={p} onPick={pick} disabled={availableSlots(p,xi,formation.slots).length===0}/>)}</div></>}</aside></div>
 {pending&&<div className="fixed inset-0 z-30 flex items-end justify-center bg-black/70 p-4 sm:items-center" onClick={()=>setPending(null)}><div className="w-full max-w-md rounded-3xl border border-white/15 bg-[#132219] p-6" onClick={e=>e.stopPropagation()}><p className="text-xs uppercase tracking-widest text-lime">Choose a position</p><h3 className="display mt-1 text-3xl">{pending.name}</h3><div className="mt-5 grid grid-cols-2 gap-3">{availableSlots(pending,xi,formation.slots).map(s=><button key={s.id} onClick={()=>place(pending,s.id)} className="rounded-xl border border-white/15 p-4 text-left hover:border-lime hover:bg-lime hover:text-ink"><b className="display block text-xl">{s.role}</b><small>{s.label}</small></button>)}</div></div></div>}
 </main>
}
